/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BadERC20 } from "./BadERC20";
export type { TestERC20 } from "./TestERC20";
export type { User } from "./User";
export type { VM } from "./VM";
