/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20FaucetTSol from "./ERC20Faucet.t.sol";
export * as ethFaucetTSol from "./ETHFaucet.t.sol";
export * as faucetFactoryTSol from "./FaucetFactory.t.sol";
export * as strategies from "./strategies";
export * as utils from "./utils";
