/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as faucetMetadataRendererSol from "./FaucetMetadataRenderer.sol";
export type { faucetMetadataRendererSol };
import type * as external from "./external";
export type { external };
export type { IFaucetMetadataRenderer } from "./IFaucetMetadataRenderer";
