/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IZorbRenderer,
  IZorbRendererInterface,
} from "../../FaucetMetadataRenderer.sol/IZorbRenderer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "zorbForAddress",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IZorbRenderer__factory {
  static readonly abi = _abi;
  static createInterface(): IZorbRendererInterface {
    return new utils.Interface(_abi) as IZorbRendererInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IZorbRenderer {
    return new Contract(address, _abi, signerOrProvider) as IZorbRenderer;
  }
}
