/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  DailyStepStrategy,
  DailyStepStrategyInterface,
} from "../DailyStepStrategy";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_totalAmt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_faucetStart",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_faucetExpiry",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_timestamp",
        type: "uint256",
      },
    ],
    name: "claimableAtTimestamp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102c2806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806301ffc9a71461003b5780637aefca24146100a5575b600080fd5b610090610049366004610153565b7fffffffff00000000000000000000000000000000000000000000000000000000167f7aefca24000000000000000000000000000000000000000000000000000000001490565b60405190151581526020015b60405180910390f35b6100b86100b336600461019c565b6100c6565b60405190815260200161009c565b6000838210156100d85750600061014b565b8282106100e657508361014b565b6000620151806100f686866101fd565b6101009190610214565b90508061011157600091505061014b565b600061011d8288610214565b905060006201518061012f88876101fd565b6101399190610214565b9050610145828261024f565b93505050505b949350505050565b60006020828403121561016557600080fd5b81357fffffffff000000000000000000000000000000000000000000000000000000008116811461019557600080fd5b9392505050565b600080600080608085870312156101b257600080fd5b5050823594602084013594506040840135936060013592509050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b60008282101561020f5761020f6101ce565b500390565b60008261024a577f4e487b7100000000000000000000000000000000000000000000000000000000600052601260045260246000fd5b500490565b6000817fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0483118215151615610287576102876101ce565b50029056fea26469706673582212207562fb133cddb18e374aa3f1cabaa5794e794de9568962439bb9a01bea46b2b864736f6c634300080c0033";

type DailyStepStrategyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DailyStepStrategyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DailyStepStrategy__factory extends ContractFactory {
  constructor(...args: DailyStepStrategyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DailyStepStrategy> {
    return super.deploy(overrides || {}) as Promise<DailyStepStrategy>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): DailyStepStrategy {
    return super.attach(address) as DailyStepStrategy;
  }
  override connect(signer: Signer): DailyStepStrategy__factory {
    return super.connect(signer) as DailyStepStrategy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DailyStepStrategyInterface {
    return new utils.Interface(_abi) as DailyStepStrategyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DailyStepStrategy {
    return new Contract(address, _abi, signerOrProvider) as DailyStepStrategy;
  }
}
