/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as deploySSol from "./Deploy.s.sol";
export type { deploySSol };
import type * as deployDepsSSol from "./DeployDeps.s.sol";
export type { deployDepsSSol };
import type * as deployStrategiesSSol from "./DeployStrategies.s.sol";
export type { deployStrategiesSSol };
