/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BadERC20__factory } from "./BadERC20__factory";
export { TestERC20__factory } from "./TestERC20__factory";
export { User__factory } from "./User__factory";
export { VM__factory } from "./VM__factory";
