/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20FaucetTSol from "./ERC20Faucet.t.sol";
export type { erc20FaucetTSol };
import type * as ethFaucetTSol from "./ETHFaucet.t.sol";
export type { ethFaucetTSol };
import type * as faucetFactoryTSol from "./FaucetFactory.t.sol";
export type { faucetFactoryTSol };
import type * as strategies from "./strategies";
export type { strategies };
import type * as utils from "./utils";
export type { utils };
