/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testSol from "./Test.sol";
export type { testSol };
export type { Script } from "./Script";
export type { Vm } from "./Vm";
