/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as renderer from "./renderer";
export type { renderer };
import type * as scripts from "./scripts";
export type { scripts };
import type * as strategies from "./strategies";
export type { strategies };
import type * as test from "./test";
export type { test };
export type { ERC20Faucet } from "./ERC20Faucet";
export type { ETHFaucet } from "./ETHFaucet";
export type { FaucetFactory } from "./FaucetFactory";
export type { IFaucet } from "./IFaucet";
export type { IFaucetFactory } from "./IFaucetFactory";
